import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  renderToStream,
  Image,
} from "@react-pdf/renderer";
import fs from "fs";
import path from "path";
import crypto from "crypto";
import { prisma } from "@/lib/prisma";

export async function generatePdfCV(userId: string) {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    include: {
      profile: true,
      skills: true,
      experiences: true,
    },
  });

  if (!user || !user.profile) {
    throw new Error("Profile not found");
  }

  const filename = `cv-${crypto.randomUUID()}.pdf`;
  const dir = path.join(process.cwd(), "public/uploads/cv");
  fs.mkdirSync(dir, { recursive: true });

  const filePath = path.join(dir, filename);

  const styles = StyleSheet.create({
    page: {
      padding: 40,
      fontSize: 11,
      fontFamily: "Helvetica",
      lineHeight: 1.5,
    },

    header: {
      marginBottom: 28,
    },

    headerRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
    },

    logo: {
      width: 90,
      height: "auto",
    },

    name: {
      fontSize: 24,
      fontWeight: "bold",
      marginBottom: 6,
    },

    email: {
      fontSize: 11,
      marginBottom: 8,
    },

    meta: {
      fontSize: 10,
      color: "#6b7280",
      marginBottom: 2,
    },

    textMuted: {
      fontSize: 10,
      color: "#6b7280",
    },

    section: {
      marginTop: 20,
    },

    sectionTitle: {
      fontSize: 14,
      fontWeight: "bold",
      marginBottom: 8,
      borderBottom: "1 solid #e5e7eb",
      paddingBottom: 4,
    },

    experienceItem: {
      marginBottom: 12,
    },

    jobTitle: {
      fontWeight: "bold",
      fontSize: 11,
    },
  });

  const logoPath = path.join(process.cwd(), "public/logo/blue.png");
  const logoBase64 = fs.readFileSync(logoPath).toString("base64");
  const logoSrc = `data:image/png;base64,${logoBase64}`;

  const pdf = (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* HEADER */}
        <View style={styles.header}>
          <View style={styles.headerRow}>
            <View>
              <Text style={styles.name}>{user.profile.name}</Text>
              <Text style={styles.email}>{user.email}</Text>

              {user.profile.gender && (
                <Text style={styles.meta}>Gender: {user.profile.gender}</Text>
              )}

              {user.profile.dob && (
                <Text style={styles.meta}>
                  Date of Birth:{" "}
                  {new Date(user.profile.dob).toLocaleDateString()}
                </Text>
              )}
            </View>

            <Image src={logoSrc} style={styles.logo} />
          </View>
        </View>

        {/* BIO */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Profile</Text>
          <Text>{user.profile.bio || "-"}</Text>
        </View>

        {/* SKILLS */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Skills</Text>
          {user.skills.length ? (
            user.skills.map((skill) => (
              <Text key={skill.id}>• {skill.name}</Text>
            ))
          ) : (
            <Text>-</Text>
          )}
        </View>

        {/* EXPERIENCE */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Work Experience</Text>

          {user.experiences.length ? (
            user.experiences.map((exp) => (
              <View key={exp.id} style={styles.experienceItem}>
                <Text style={styles.jobTitle}>{exp.jobTitle}</Text>
                <Text>{exp.companyName}</Text>
                <Text style={styles.textMuted}>
                  {new Date(exp.startDate).toLocaleDateString()} –{" "}
                  {exp.endDate
                    ? new Date(exp.endDate).toLocaleDateString()
                    : "Present"}
                </Text>
              </View>
            ))
          ) : (
            <Text>-</Text>
          )}
        </View>

        <Text
          style={{
            position: "absolute",
            bottom: 30,
            left: 40,
            right: 40,
            fontSize: 9,
            color: "#9ca3af",
            textAlign: "center",
          }}
        >
          This CV was generated by EduTIA
        </Text>
      </Page>
    </Document>
  );

  const stream = await renderToStream(pdf);
  const writeStream = fs.createWriteStream(filePath);

  await new Promise<void>((resolve) => {
    stream.pipe(writeStream);
    writeStream.on("finish", resolve);
  });

  const url = `/uploads/cv/${filename}`;

  await prisma.cV.create({
    data: {
      fileUrl: url,
      user: {
        connect: { id: userId },
      },
    },
  });

  return url;
}
